### ISSUE TITLE
NW file for linux export should be renamed to Game

### ISSUE THREAD

**Issue by auragamedev** [erri120/rpgmpacker#39]
**Version Information:**
 - RPGMPacker Version: 1.6.0
 - RPG Maker Version: MZ

New export to Linux works great. 
It would be neat if the "nw" file could also be automatically renamed to "Game" as I think it also happens for the nw.exe in nwjs-win.

**Log:**
https://gist.github.com/auragamedev/575d90670c26a0c3dcbe5f9ab56c7d78

**Comment by erri120** [comment]
faa107751ced7f1fedf1df405267d26d76b951f4
