### ISSUE TITLE
libffmpeg.dylib seems to be missing in OSX deployment

### ISSUE THREAD

**Issue by auragamedev** [erri120/rpgmpacker#43]
**Version Information:**
 - RPGMPacker Version: 1.2.1
 - RPG Maker Version: MZ

There seems to be a hardcoded chromium version number, but RPGM changed the nwjs versions and with it also the chromium versions so the libffmpeg.dylib file seems to be incorrectly ignored.

https://github.com/erri120/rpgmpacker/blob/ffcb27912abb6e2d57d55a5f844a529754a58516/RPGMPackerLib/src/utility.cpp

Upper picture is export from RPGMaker, lower one using RPGMPacker.

![Screenshot 2021-04-21 14 05 47](https://user-images.githubusercontent.com/78755127/115551448-6145be00-a2ab-11eb-946c-1d7b20b8759b.png)

**Log:**
https://gist.github.com/auragamedev/91a22845e1c906f57d3d12574745bf24

**Comment by erri120** [comment]
Fixed in #44
