### ISSUE TITLE
"Change Actor Images" command doesn't mark a resource as being used

### ISSUE THREAD

**Issue by auragamedev** [erri120/rpgmpacker#49]
**Description**
Exporting while excluding unused resources also excludes resources which are only used by the "Change Actor Images" command.
If I export the game with RPGM, these resources are included in the exported game.

For reproduction, you can also check here:
https://gitgud.io/aura-dev/star_knightess_aura/-/jobs/176605

The character image aura_rl_brown.png should be in the exported game, but it is not copied.
When exporting with RPGMaker, the file is copied correctly also when exclude unused resources is selected.

**Environment Details**

- rpgmpacker Version: 2.0.4
- Node.js Version: Didn't check.
- Package Manager: npm

**Logs**
https://gist.github.com/auragamedev/77b9724f21971b6717b3d0457b9c7c55

**Comment by erri120** [comment]
https://github.com/erri120/rpgmpacker/blob/1d160b82f1b233e842b41a9055d779c51eb78b2f/src/parsedData.ts#L201-L202

hmm, I did add this event

**Comment by erri120** [comment]
The event gets parsed correctly and `auro_rl_brown` is added to the used character names list
![image](https://user-images.githubusercontent.com/16577545/155581538-7535e74a-f039-4612-854c-7293d66d93da.png)

**Comment by erri120** [comment]
![image](https://user-images.githubusercontent.com/16577545/155582602-90a2f592-b69d-45e2-97d8-5f05e534c554.png)

the file operation was also successfully created and the file was copied:

![image](https://user-images.githubusercontent.com/16577545/155582752-7e8fdd2f-c9d1-4331-a066-2058830d5ba0.png)

**Comment by erri120** [comment]
The logs say the file was not copied, I guess the only difference is I'm on Windows and the CI runs on Linux

**Comment by auragamedev** [comment]
Just to make sure: You are on the commit from the build job? fbf0462082f44c3698da19e7b178c4326ba3ce00
In the HEAD of the developement I used a workaround (added a dummy character)

**Comment by erri120** [comment]
nvm was just dumb, will be fixed in 2.0.5
