### ISSUE TITLE
Version 1.2.0 crashes on missing folders

### ISSUE THREAD

**Issue by auragamedev** [erri120/rpgmpacker#6]
Using RPGMPacker 1.2.0 on a project where a folder doesn't exist seems to cause it to crash.

![grafik](https://user-images.githubusercontent.com/78755127/107263956-a98e6780-6a42-11eb-9251-05ac1edecf2f.png)

The above worked on version 1.1.0.
This is problematic since .git doesn't check in empty folders (such as the movies folder in the screenshot).

For reproduction: https://gitgud.io/aura-dev/star_knightess_aura/-/tree/feature/task_221-Upgrade_to_RPGMPacker

**Comment by erri120** [comment]
Fixed in [1.2.1](https://github.com/erri120/rpgmpacker/releases/tag/v1.2.1).

**Comment by erri120** [comment]
btw, ich besitze nur MV und muss die MZ demo verwenden weshalb einige features bei MZ nocht nicht komplett funktionieren (OSX output und exclude unused files).
