### ISSUE TITLE
Exclude Unused Files broken with MZ

### ISSUE THREAD

**Issue by auragamedev** [erri120/rpgmpacker#7]
Version: RPGMPacker version 1.2.1.

![Screenshot 2021-02-08 19 51 49](https://user-images.githubusercontent.com/78755127/107267550-55d24d00-6a47-11eb-891b-4e1a3318b847.png)

I sadly can't tell any further what's going wrong.

Reproduction: https://gitgud.io/aura-dev/star_knightess_aura/-/tree/feature/task_221-Upgrade_to_RPGMPacker

**Comment by erri120** [comment]
Enable debug output with `--debug` for more information.

**Comment by auragamedev** [comment]
Calling RPGMPacker with --debug

![grafik](https://user-images.githubusercontent.com/78755127/107268359-53bcbe00-6a48-11eb-8a01-8e3374c33288.png)

**Comment by erri120** [comment]
You should disable "Exclude Unused Files" for now. I haven't tested that with MZ yet.

**Comment by auragamedev** [comment]
@erri120 alright, will put my upgrade ticket on hold then. Btw great work with the tool.

**Comment by erri120** [comment]
1.3.0 should fix this https://github.com/erri120/rpgmpacker/releases/tag/v1.3.0
